name: Docker Image CI

on:
  push:
    branches: [ "main", "ruby*.*.*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:

    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
        with:
          driver-opts: network=host
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: true
          tags: localhost:5000/atis9/ruby-with-mecab:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test
        run: docker run --rm localhost:5000/atis9/ruby-with-mecab:test ruby -e "require 'natto'; nm = Natto::MeCab.new; exit(1) if nm.version != '0.996';"
